apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: docling-spark-job
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  # Using pinned digest to ensure image with PDFs is used
  image: quay.io/rishasin/docling-spark@sha256:8c51dbbd02b51e00ad8fa60da68cafb983b29dbdfa6533ebd4daba119fe9c953
  imagePullPolicy: IfNotPresent
  timeToLiveSeconds: 1200  # <--- (Keeps pod for 20 minutes)
  mainApplicationFile: local:///app/scripts/run_spark_job.py
  arguments:
    - "--input-dir"
    - "/app/assets"
    - "--output-file"
    - "/app/output/results.jsonl"
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "4g"
    labels:
      version: 3.5.0
    serviceAccount: spark-driver
    securityContext: {}
  executor:
    cores: 1
    instances: 2
    memory: "4g"
    labels:
      version: 3.5.0
    securityContext: {}
